class Data {
  static List photo = [
    "back.jpg",
    "Diwali.jpg",
    "gt2.jpg",
    "kkr1.jpg",
    "mi1.jpg",
    "mi2.jpg",
    "mi3.jpg",
    "mi6.jpg",
    "rcb1.jpg",
    "rcb4.jpg",
    "rcb6.jpg",
    "gt7.jpg",
    "fun.jpg",
    "ganesha.jpg",
    "god.jpg",
    "guru.jpg",
    "men.jpg",
    "mrbean.jpg",
    "politic.jpg",
    "shiva1.jpg",
    "shopping.jpg",
    "sikh.jpg",
  ];
}